START TRANSACTION;

DROP TABLE IF EXISTS potholes;
DROP TABLE IF EXISTS users;

CREATE TABLE users
(
    user_id int GENERATED BY DEFAULT AS IDENTITY,
    email varchar(64) NOT NULL UNIQUE,
    password varchar(32) NOT NULL,
    role varchar(255) NOT NULL default('user'),

    CONSTRAINT pk_user PRIMARY KEY (id)
);

CREATE TABLE potholes
(
    id int GENERATED BY DEFAULT AS IDENTITY,
    latitude decimal(15,10) NOT NULL,
    longitude decimal(15,10) NOT NULL,
    rating varchar(16) NOT NULL,
    comments varchar(256),
    user_id int NOT NULL,

    CONSTRAINT pk_pothole PRIMARY KEY (id),
    CONSTRAINT fk_pothole_user FOREIGN KEY (user_id) REFERENCES users (user_id)
);

COMMIT TRANSACTION;