START TRANSACTION;

DROP TABLE IF EXISTS markers;
DROP TABLE IF EXISTS users;

CREATE TABLE users
(
    user_id int GENERATED BY DEFAULT AS IDENTITY,
    username varchar(64) NOT NULL UNIQUE,
    password varchar(32) NOT NULL,
    role varchar(255) NOT NULL default('user'),

    CONSTRAINT pk_user PRIMARY KEY (user_id)
);

CREATE TABLE markers
(
    marker_id int GENERATED BY DEFAULT AS IDENTITY,
    latitude varchar(64) NOT NULL,
    longitude varchar(64) NOT NULL,
    rating varchar(16) NOT NULL,
    comments varchar(256),
    user_id int NOT NULL,

    CONSTRAINT pk_marker PRIMARY KEY (marker_id),
    CONSTRAINT fk_marker_user FOREIGN KEY (user_id) REFERENCES users (user_id)
);


INSERT INTO users (username, password, role) 
VALUES ('test1', 'testpass1', 'user');

INSERT INTO users (username, password, role) 
VALUES ('test2', 'testpass2', 'user');

INSERT INTO users (username, password, role) 
VALUES ('test3', 'testpass3', 'user');


INSERT INTO markers (latitude, longitude, rating, comments, user_id) 
VALUES ('39.193684289509065', '-84.32208179208072', 'moderate', 
        'Not too bad. Located on the left side of the road.', 2);

INSERT INTO markers (latitude, longitude, rating, comments, user_id) 
VALUES ('39.22214908061195', '-84.36568378182682', 'severe', 
        'Fairly deep and in the middle of the road. Definitely avoid.', 3);

INSERT INTO markers (latitude, longitude, rating, comments, user_id) 
VALUES ('39.22214908061195', '-84.36568378182682', 'critical', 
        'Very deep and covers almost half the road. Cracked 2 of my rims', 1);

COMMIT TRANSACTION;


-- SELECT marker_id, latitude, longitude, rating, comments, user_id 
-- FROM markers;

-- SELECT marker_id, latitude, longitude, rating, comments, user_id 
-- FROM markers
-- WHERE marker_id = ?;

-- SELECT marker_id, latitude, longitude, rating, comments, user_id 
-- FROM markers
-- WHERE user_id = ?;

-- SELECT marker_id, latitude, longitude, rating, comments, user_id 
-- FROM markers
-- WHERE rating = ?;

-- INSERT INTO users (email, password, role) 
-- VALUES (?, ?, ?);

-- INSERT INTO markers (latitude, longitude, rating, comments, user_id) 
-- VALUES (?, ?, ?, ?, ?);