START TRANSACTION;

DROP TABLE IF EXISTS users;

CREATE TABLE users
(
    id int GENERATED BY DEFAULT AS IDENTITY,
    email varchar(64) NOT NULL UNIQUE,
    password varchar(32) NOT NULL,
    salt varchar(256) NOT NULL,
    role varchar(255) NOT NULL default('user'),

    CONSTRAINT pk_user PRIMARY KEY (id)
);

COMMIT TRANSACTION;